<?php
/**
 * Dashboard Controller — the overview, as a file.
 *
 * The dashboard itself is still a plain view included by the router; there is
 * no index() here and nothing to gain from adding one. What this controller
 * exists for is the Export button in the page header, which for a long time
 * pointed at "#" and did nothing.
 *
 * The export is a snapshot of the page, not a new report. Every section below
 * reads the same function the screen reads — dashboardStatCards(),
 * dashboardRevenueSeries(), propertyStatusBreakdown(), dashboardRecentActivity()
 * — so the file and the page cannot quote different numbers. Anything the
 * reader is not allowed to see on the page is absent from the file rather than
 * blank in it, gated on the same permission the page gates the panel on.
 *
 * CSV rather than PDF or XLSX: the point of the button is to get these figures
 * into whatever the person reading them already works in, and every
 * spreadsheet on earth opens a CSV. It is also the only format this
 * application can produce with no dependency and no temporary file.
 */
require_once BASE_PATH . '/includes/dashboard.php';

class DashboardController
{
    /** How much of the audit trail travels with the snapshot. */
    private const ACTIVITY_ROWS = 50;

    /**
     * Stream the dashboard as a CSV attachment.
     *
     * `dashboard.export` is held by the administrator's wildcard and by nobody
     * else, which is deliberate: the figures on this page are portfolio-wide
     * and unscoped — every customer, every payment, the whole user list — so
     * the file is for the role that already sees all of it on screen. An agent
     * has `dashboard.view` and gets their own dashboard; a hand-typed
     * ?action=export gets them a 403, not the company's arrears.
     */
    public function export(): void
    {
        authorize('dashboard.export');

        $rows = $this->snapshot();

        // Recorded like any other read of the whole portfolio. The trail says
        // a copy left the building, which is the question asked afterwards.
        logAudit('exported_dashboard', 'dashboard', 0, '', date('Y-m-d H:i:s'));

        $this->stream('dashboard-' . date('Y-m-d') . '.csv', $rows);
    }

    // ─── The file ──────────────────────────────────────────────────────

    /**
     * The snapshot, as rows. Building it in one place keeps the section order
     * readable and keeps every header string next to the figures under it.
     *
     * @return array<int, array<int, string|int|float>>
     */
    private function snapshot(): array
    {
        $user = getCurrentUser();

        $rows = [
            [companyName() . ' — Dashboard snapshot'],
            ['Generated', date('Y-m-d H:i')],
            ['Generated by', (string) ($user['full_name'] ?? 'Unknown')],
            ['Currency', currencyCode()],
        ];

        // ── The six headline figures ──
        $rows[] = [];
        $rows[] = ['Key figures'];
        $rows[] = ['Metric', 'Value', 'Note'];
        foreach (dashboardStatCards() as $card) {
            $rows[] = [$card['label'], (int) $card['value'], (string) ($card['note'] ?? '')];
        }

        // ── Revenue ──
        // Money follows the Reports permission here exactly as it does on the
        // page, where a role without it is never handed the trend.
        if (can('reports.view')) {
            $series = dashboardRevenueSeries();
            $rows[] = [];
            $rows[] = ['Revenue — payments received, last 6 months'];
            $rows[] = ['Month', 'Amount (' . currencyCode() . ')'];
            foreach ($series as $month) {
                // The bare number, not formatCurrency(): a spreadsheet has to
                // be able to add this column up, and a thousands separator in
                // front of a currency symbol is text.
                $rows[] = [$month['full'], number_format($month['total'], 2, '.', '')];
            }
            $rows[] = ['Total', number_format(array_sum(array_column($series, 'total')), 2, '.', '')];
        }

        // ── Properties by status ──
        if (can('properties.view')) {
            $breakdown = propertyStatusBreakdown();
            if ($breakdown) {
                $rows[] = [];
                $rows[] = ['Properties by status — live listings, archived excluded'];
                $rows[] = ['Status', 'Count', 'Share %'];
                foreach ($breakdown as $slice) {
                    $rows[] = [$slice['label'], (int) $slice['count'], round((float) $slice['pct'], 1)];
                }
                $rows[] = ['Total', array_sum(array_column($breakdown, 'count')), 100];
            }
        }

        // ── Recent activity ──
        if (can('audit-logs.view')) {
            $activity = dashboardRecentActivity(self::ACTIVITY_ROWS);
            if ($activity) {
                $rows[] = [];
                $rows[] = ['Recent activity — newest ' . count($activity)];
                $rows[] = ['When', 'User', 'Action', 'Entity', 'Entity ID'];
                foreach ($activity as $entry) {
                    $rows[] = [
                        (string) ($entry['created_at'] ?? ''),
                        (string) ($entry['full_name'] ?? 'System'),
                        (string) ($entry['action'] ?? ''),
                        (string) ($entry['entity_type'] ?? ''),
                        (int) ($entry['entity_id'] ?? 0),
                    ];
                }
            }
        }

        return $rows;
    }

    /**
     * Send rows as a CSV download and stop.
     *
     * The buffer teardown and session_write_close() are the same two lines
     * streamStoredFile() opens with, and for the same reasons: views render
     * inside ob_start(), and a download should not hold the session lock while
     * the user's other tabs wait on it.
     *
     * @param array<int, array<int, string|int|float>> $rows
     */
    private function stream(string $filename, array $rows): never
    {
        if (session_status() === PHP_SESSION_ACTIVE) {
            session_write_close();
        }
        while (ob_get_level() > 0) {
            ob_end_clean();
        }

        header('Content-Type: text/csv; charset=UTF-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('X-Content-Type-Options: nosniff');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: no-cache');

        $out = fopen('php://output', 'w');

        // Excel reads a CSV as the machine's legacy codepage unless the file
        // says otherwise, which turns every currency symbol and em dash in
        // here into mojibake. The BOM is what makes it read UTF-8.
        fwrite($out, "\xEF\xBB\xBF");

        foreach ($rows as $row) {
            fputcsv($out, array_map([$this, 'cell'], $row));
        }

        fclose($out);
        exit;
    }

    /**
     * Defuse a cell a spreadsheet would run instead of read.
     *
     * Names, actions and entity types in this file were typed by people. Excel
     * and Sheets treat a leading =, +, - or @ as the start of a formula, so a
     * customer called `=HYPERLINK(...)` becomes a live cell in whoever's
     * spreadsheet this lands in. Prefixing a tab keeps the text visible and
     * makes the cell inert; quoting alone does not.
     */
    private function cell(string|int|float|null $value): string
    {
        $text = (string) $value;

        return $text !== '' && str_contains("=+-@\t\r", $text[0]) ? "\t" . $text : $text;
    }
}
